const Images = {
  navLogo: require("./logo.png"),
  cart: require("./cart.png"),
  emptyCart: require("./emptyCart.png"),
  sliderPicOne: require("./slider_pic_one.png"),
  sliderPicTwo: require("./slider_pic_two.png"),
  sliderPicThree: require("./slider_pic_three.png"),
  confiti: require("./confetti_icon.png"),
  techIcon: require("./icon.png"),
  middelMotiva: require("./middel-motiva.png"),
  strockSmall: require("./strock_small.png"),
  sadFace: require("./sadFace.png"),
  motherboardIcon: require("./categotyIcons/motherboardIcon.png"),
  processorIcon: require("./categotyIcons/processorIcon.png"),
  memoryIcon: require("./categotyIcons/ramIcon.png"),
  graphicCardIcon: require("./categotyIcons/videoCardIcon.png"),
  caseIcon: require("./categotyIcons/caseIcon.png"),
  powerSupplyIcon: require("./categotyIcons/powerUnitIcon.png"),
  liquidCoolingIcon: require("./categotyIcons/radiatorIcon.png"),
  airCoolingIcon: require("./categotyIcons/fanIcon.png"),
  ssdIcon: require("./categotyIcons/ssdIcon.png"),
  hddIcon: require("./categotyIcons/hddIcon.png"),
  monitorIcon: require("./categotyIcons/monitorIcon.png"),
  chairIcon: require("./categotyIcons/chairIcon.png"),
  mouseIcon: require("./categotyIcons/mouseIcon.png"),
  mousePadIcon: require("./categotyIcons/mousePadIcon.png"),
  keyboardIcon: require("./categotyIcons/keyboardIcon.png"),
  headsetIcon: require("./categotyIcons/headsetIcon.png"),
};
export default Images;
